# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0002_auto_20160226_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='text_title',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='writer',
        ),
    ]
