# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0003_auto_20160226_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='correspond_img',
            field=models.ImageField(default='', height_field=200, max_length=30, upload_to='uploads/', width_field=324),
        ),
        migrations.AddField(
            model_name='summary',
            name='correspond_img',
            field=models.ImageField(default='', height_field=100, max_length=30, upload_to='uploads/', width_field=162),
        ),
        migrations.AddField(
            model_name='summary',
            name='head',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='summary',
            name='sub_head',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.CharField(default='管理人', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='text_title',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='experience',
            name='writer',
            field=models.CharField(default='管理人', max_length=10),
        ),
    ]
