# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0004_auto_20160228_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(max_length=30)),
                ('link_text', models.CharField(max_length=100)),
                ('urllink', models.URLField(max_length=100)),
            ],
        ),
    ]
