# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0005_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='correspond_img',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correspond_img',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='keys',
            name='article_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveinfo.Article'),
        ),
        migrations.AddField(
            model_name='keys',
            name='experince_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveinfo.Experience'),
        ),
    ]
