# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 19:54
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0006_auto_20160301_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='article_key',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='experince_key',
        ),
        migrations.AlterField(
            model_name='article',
            name='main_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='main_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='summary',
            name='main_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Keys',
        ),
    ]
