# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0008_auto_20160306_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='correspond_img',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='correspond_img',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
