# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0009_auto_20160306_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='correspond_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='correspond_img',
            new_name='img',
        ),
    ]
