# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0013_auto_20160312_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
