# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 15:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0015_auto_20160312_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='head',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='pic_name',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='sub_head',
        ),
        migrations.AlterField(
            model_name='summary',
            name='main_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
