# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 19:47
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveinfo', '0020_auto_20161112_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='main_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='experiencetext',
            name='main_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
