# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsnew',
            name='new_date',
        ),
        migrations.AddField(
            model_name='whatsnew',
            name='link_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='whatsnew',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
