# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_page', '0002_auto_20160227_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsnew',
            name='link_text',
            field=models.CharField(default='top_page', max_length=100),
        ),
    ]
