# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top_page', '0004_positive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Positive',
        ),
    ]
