# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_page', '0005_delete_positive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('event_venue', models.CharField(max_length=100)),
                ('venue_link', models.URLField()),
                ('event_text', models.CharField(max_length=100)),
            ],
        ),
    ]
